id: P91F47166
initial_creation_type: ocr
source_metadata:
  volumes:
    52460473d78f4940b318d441c020ac5f:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
