id: DF6EEAADF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-08T09:37:15+00:00'
last_modified: '2022-05-30T07:35:45.282612+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    1f27:
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      order: 47
      base_file: 1f27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
